sudo: required
services:
        - docker

before_install:
        - docker build -t urira/docker-react -f Dockerfile.dev .
scripts:
        - docker run urira/docker-react npm run test -- --coverage
