sudo: required
services:
        - docker
before_install:
        - docker build -t urira/docker-react -f Dockerfile.dev .
scripts:
        - docker run  -e CI=true urira/docker-react npm run test -- --coverage

deploy:
        provider: elasticbeanstalk
        region: "eu-west-1"
        app: "docker-react-sample"
        env: "DockerReactSample-env"
        bucket_name: "elasticbeanstalk-eu-west-1-742434153745"
        bucket_path: "docker-react"
        on:
                branch: master
        access_key_id: "$AWS_ACCESS_KEY_ID"
        secret_access_key:
                secure: "$AWS_SECRET_ACCESS_KEY"
